[tox]
minversion = 2.5.0
envlist = py{311,313}-{style,unit,mypy}
skip_missing_interpreters = True

[testenv]
usedevelop = True
basepython =
    py311: python3.11
    py313: python3.13
description =
    style: Style consistency checker
    unit: Run unit tests.
    py311: (Python 3.11)
    py313: (python 3.13)

commands =
    style: flake8
    style: black --config black.toml --check .
    unit: pytest --cov=docker_report tests/ --cov-report=term-missing
    mypy: mypy --config-file mypy.ini docker_report

deps =
    style: flake8
    style: black
    unit: pytest-cov
    unit: requests-mock
    mypy: mypy
    mypy: types-requests
    mypy: types-PyYAML


[flake8]
max-line-length = 120
statistics = True
exclude = .venv,.eggs,.tox,build
